[package]
name = "oxidio-web"
description = "Web server and WebSocket handler for Oxidio"
readme = "../../README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
oxidio-protocol.workspace = true
oxidio-ctl.workspace = true
tokio.workspace = true
tracing.workspace = true
axum.workspace = true
tower-http.workspace = true
serde_json.workspace = true
rust-embed.workspace = true
mime_guess.workspace = true
futures-util.workspace = true
